### ISSUE TITLE
Problems with fibers installing on Raspberry Pi

### ISSUE THREAD

**Issue by guillemhs** [webdriverio/wdio-mocha-framework#145]
Hi,
I pulled the code on a Raspberry and I have node version 7.8.0.
I have problems with Fibers.
The problem is as follows:
```
root@raspberrypi:~/appium-hbbtv-driver# npm install /root/wdio-mocha-framework
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm WARN lifecycle wdio-mocha-framework@0.5.13~prepublish: cannot run in wd %s %s (wd=%s) wdio-mocha-framework@0.5.13 npm prune && run-s build test /root/wdio-mocha-framework

> fibers@2.0.2 install /root/appium-hbbtv-driver/node_modules/fibers
> node build.js || nodejs build.js

module.js:327
    throw err;
    ^

Error: Cannot find module '/root/appium-hbbtv-driver/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
module.js:327
    throw err;
    ^

Error: Cannot find module '/root/appium-hbbtv-driver/node_modules/fibers/build.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
appium-hbbtv-driver@0.0.0 /root/appium-hbbtv-driver
├── he@1.1.1  extraneous
└── UNMET PEER DEPENDENCY webpack@4.6.0 extraneous

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
npm ERR! Linux 4.14.34-v7+
npm ERR! argv "/root/.nvm/versions/node/v7.8.0/bin/node" "/root/.nvm/versions/node/v7.8.0/bin/npm" "install" "/root/wdio-mocha-framework"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@2.0.2 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2018-04-25T15_23_03_498Z-debug.log
```

Do you know how can I fix it?

**Comment by christian-bromann** [comment]
> Do you know how can I fix it?

No, just use an older NodeJS version. Probably worth filing this issue in the fibers project. There is nothing much really that can be fixed here.
