### ISSUE TITLE
Show full info about fails

### ISSUE THREAD

**Issue by monolithed** [webdriverio/wdio-mocha-framework#24]
#### Test

```js
let assert = require('assert');

describe('test', () => {
	it('case', () => {
		assert.equal(1, 2, 'some text');
	});
});  
```

#### Config

```js
{
	framework: 'mocha',

	mochaOpts: {
		'ui': 'bdd',
		'trace': true,
		'full-trace': true
	}
}
```

#### wdio-mocha-framework

```diff
[chrome #0a] Running: chrome
[chrome #0a]
[chrome #0a]   test
[chrome #0a]       1) case
[chrome #0a]
[chrome #0a]
[chrome #0a] 1 failing (2s)
[chrome #0a]
[chrome #0a] 1) 1 case:
[chrome #0a] some text
[chrome #0a] AssertionError: some text
[chrome #0a]     at Context.it (/tests/cases/login/TESTMAIL-8674.js:11:21)
[chrome #0a]
```

#### wdio-mocha-framework + try / catch

```js
let assert = require('assert');

describe('test', () => {
	it('case', () => {
                try {
			assert.equal(1, 2, 'some text');
		}
		catch (error) {
			console.log(error)
			throw new Error(error);
		}
	});
});  
```

```
{ AssertionError: some text
    at Context.error (/tests/cases/login/TESTMAIL-8674.js:12:21)
    at /tests/node_modules/wdio-sync/build/index.js:659:26
    at Context.executeSync (/tests/node_modules/wdio-sync/build/index.js:657:12)
    at /tests/node_modules/wdio-sync/build/index.js:883:34
  name: 'AssertionError',
  actual: 1,
  expected: 2,
  operator: '==',
  message: 'some text',
  generatedMessage: false }
------------------------------------------------------------------
[chrome #0a] Session ID: 8b836530-2d16-48b0-a8a5-ad8c5aec9170
[chrome #0a] Spec: /tests/cases/login/TESTMAIL-8674.js
[chrome #0a] Running: chrome
[chrome #0a]
[chrome #0a]   test
[chrome #0a]       1) case
[chrome #0a]
[chrome #0a]
[chrome #0a] 1 failing (1s)
[chrome #0a]
[chrome #0a] 1) test case:
[chrome #0a] AssertionError: some text
[chrome #0a] Error: AssertionError: some text
[chrome #0a]     at Context.error (/tests/cases/login/TESTMAIL-8674.js:16:10)
[chrome #0a]
```

#### mocha

```diff
  1) test

  0 passing (13ms)
  1 failing

  1)  test:

      AssertionError: some text
      + expected - actual

      -1
      +2
      
      at Context.<anonymous> (test.js:4:12)
```

**wdio-mocha-framework**
![img-2016-09-09-15-21-31](https://cloud.githubusercontent.com/assets/803674/18386682/26ef602a-76a1-11e6-9c48-9ec496bddf56.png)

**mocha**
![img-2016-09-09-15-23-17](https://cloud.githubusercontent.com/assets/803674/18386720/5d91db30-76a1-11e6-9a2e-2718fd109e70.png)

I don't like using try / catch everywhere.  Is there any way how to see more info about fails?
PS: The problem actual for wdio exceptions as well.

**Comment by christian-bromann** [comment]
With chai you can get these kind of error messages. However this is rather an issue of the wdio spec reporter than the mocha framework
