### ISSUE TITLE
`fibers` issue on circleci.com

### ISSUE THREAD

**Issue by xpepermint** [webdriverio/wdio-mocha-framework#30]
I'm getting the error below when I run `wdio wdio.conf.js` on circleci.com.

```
[0] Running on http://10.0.4.1:4001 [copied to clipboard]
[1] ## There is an issue with `node-fibers` ##
[1] `/home/ubuntu/myproject/node_modules/wdio-mocha-framework/node_modules/wdio-sync/node_modules/fibers/bin/linux-x64-51/fibers.node` is missing.
[1]
[1] Try running this to fix the issue: /opt/circleci/nodejs/v7.5.0/bin/node /home/ubuntu/myproject/node_modules/wdio-mocha-framework/node_modules/wdio-sync/node_modules/fibers/build
[1] ERROR: Couldn't initialise framework "wdio-mocha-framework".
[1] Error: Missing binary. See message above.
[1]     at Object.<anonymous> (/home/ubuntu/myproject/node_modules/wdio-mocha-framework/node_modules/wdio-sync/node_modules/fibers/fibers.js:20:8)
[1]     at Module._compile (module.js:571:32)
[1]     at Object.Module._extensions..js (module.js:580:10)
[1]     at Module.load (module.js:488:32)
[1]     at tryModuleLoad (module.js:447:12)
[1]     at Function.Module._load (module.js:439:3)
[1]     at Module.require (module.js:498:17)
[1]     at require (internal/module.js:20:19)
[1]     at Object.<anonymous> (/home/ubuntu/myproject/node_modules/wdio-mocha-framework/node_modules/wdio-sync/node_modules/fibers/future.js:2:13)
[1]     at Module._compile (module.js:571:32)
[1]
[1]     at Runner.initialiseFramework (/home/ubuntu/myproject/node_modules/webdriverio/build/lib/runner.js:561:27)
[1]     at Runner._callee3$ (/home/ubuntu/myproject/node_modules/webdriverio/build/lib/runner.js:120:55)
[1]     at tryCatch (/home/ubuntu/myproject/node_modules/webdriverio/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:64:40)
[1]     at Generator.invoke [as _invoke] (/home/ubuntu/myproject/node_modules/webdriverio/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:355:22)
[1]     at Generator.prototype.(anonymous function) [as next] (/home/ubuntu/myproject/node_modules/webdriverio/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:116:21)
[1]     at step (/home/ubuntu/myproject/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
[1]     at /home/ubuntu/myproject/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
[1]     at F (/home/ubuntu/myproject/node_modules/webdriverio/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
[1]     at Runner.<anonymous> (/home/ubuntu/myproject/node_modules/webdriverio/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
[1]     at Runner.run (/home/ubuntu/myproject/node_modules/webdriverio/build/lib/runner.js:351:29)
```

**Comment by christian-bromann** [comment]
@xpepermint what node version are you running there?

**Comment by christian-bromann** [comment]
oh v7.5.0

**Comment by xpepermint** [comment]
Thanks @christian-bromann for your quick response. I tried with diferent 7.X versions.

**Comment by christian-bromann** [comment]
either use Node v6.X or use this solution: https://github.com/laverdet/node-fibers/issues/331

**Comment by xpepermint** [comment]
Hum... thanks for that. I'm not sure I get it just yet.

**Comment by christian-bromann** [comment]
> I'm not sure I get it just yet.

What do you mean?

**Comment by christian-bromann** [comment]
I just closed the issue because it is a dependency issue and not something that can be fixed in this project. Feel free to also reach for support on the WebdriverIO Gitter channel.

**Comment by xpepermint** [comment]
I wonder how to transform 
```
+env:
+  - CXX=g++-4.8
+
+addons:
+    apt:
+      sources:
+        - ubuntu-toolchain-r-test
+      packages:
+        - g++-4.8
```
into command line :). Can you help?

**Comment by christian-bromann** [comment]
https://discuss.circleci.com/t/using-node-js-4-0-on-circleci/26

**Comment by xpepermint** [comment]
Thanks man for your help, you are very kind. I tried that but unfortunately it doesn't work. Any other ideas?

**Comment by xpepermint** [comment]
Ref: https://github.com/laverdet/node-fibers/issues/321#issuecomment-276758931
