### ISSUE TITLE
Error when there is no suite defined

### ISSUE THREAD

**Issue by niksy** [webdriverio/wdio-mocha-framework#50]
If you don’t have suite defined (via `describe`), error is thrown:

```sh
/Users/niksy/Projects/example-project/node_modules/wdio-mocha-framework/build/adapter.js:288
                    message.parent = params.payload.parent.suites[0].title;
                                                                    ^

TypeError: Cannot read property 'title' of undefined
    at MochaAdapter.formatMessage (/Users/niksy/Projects/example-project/node_modules/wdio-mocha-framework/build/adapter.js:288:69)
    at MochaAdapter.emit (/Users/niksy/Projects/example-project/node_modules/wdio-mocha-framework/build/adapter.js:335:32)
    at emitTwo (events.js:87:13)
    at Runner.emit (events.js:172:7)
    at Runner.fail (/Users/niksy/Projects/example-project/node_modules/mocha/lib/runner.js:244:8)
    at Runner.uncaught (/Users/niksy/Projects/example-project/node_modules/mocha/lib/runner.js:717:8)
    at process.uncaught (/Users/niksy/Projects/example-project/node_modules/mocha/lib/runner.js:805:10)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:219:26)
```

Not having `describe` is valid in Mocha land, so I suppose this should also be valid with WebdriverIO?

**Comment by christian-bromann** [comment]
Not reproducible. Tried with an empty spec file as well as this:
```js
describe('test', () => {
})
```
both worked

**Comment by niksy** [comment]
@christian-bromann 

This works:

```js
const assert = require('assert');

describe('test', function () {
	it('should', function () {
		assert.ok(true);
	});
});
```

But this doesn’t:

```js
const assert = require('assert');

it('should', function () {
	assert.ok(true);
});
```

**Comment by christian-bromann** [comment]
> But this doesn’t:

@niksy Where do you see this being defined as valid spec in the Mocha documentation?

**Comment by niksy** [comment]
@christian-bromann 

https://mochajs.org/#bdd

> context() is just an alias for describe(), and behaves the same way; it just provides a way to keep tests easier to read and organized. Similarly, specify() is an alias for it().

Also, [various](https://gist.github.com/samwize/8877226#file-mocha-guide-to-testing-js-L4-L5) [non-official](http://stackoverflow.com/a/23578577/178058) explanations.

**Comment by christian-bromann** [comment]
@niksy I am happy to receive PRs fixing that. It might indeed be not supported but I recommend to have a top level describe block.
