### ISSUE TITLE
TypeError in test output

### ISSUE THREAD

**Issue by anjunatl** [webdriverio/wdio-mocha-framework#65]
I'm trying to get a wdio environment set up and ran across this message after switching from Jasmine to Mocha.

I don't think it has anything to do with the wdio reporter output - I got the same `TypeError` when using both `spec` and `dot` reporters. It might be related to the screenshot output, but I'm really not certain.

```
[01:10:45]     Saved screenshot: ERROR_firefox_2017-06-25T05-10-45.083Z.png
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at process.target._send (internal/child_process.js:635:23)
    at process.target.send (internal/child_process.js:547:19)
    at /usr/local/lib/node_modules/webdriverio/build/lib/runner.js:484:25
    at execHook (/usr/local/lib/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:157:35)
F

0 passing (5.20s)
1 failing

1) Login form should reject bad credentials:
An element could not be located on the page using the given search parameters ("span.help-block").
running firefox
Error: An element could not be located on the page using the given search parameters ("span.help-block").
    at Promise.F (/usr/local/lib/node_modules/wdio-mocha-framework/node_modules/core-js/library/modules/_export.js:35:28)
    at elements([object Object]) - setValue.js:29:17
    at setValue([object Object], "foo") - at Context.<anonymous> (test/specs/basic.spec.js:13:17)

```

Let me know if there's anything else I can supply that might help debug this. Thanks!

**Comment by anjunatl** [comment]
Hard to say for sure, but this error went away for me and I think it was because I didn't follow the page object examples exactly right. (Property getters being functions that return element objects.)
